### ISSUE TITLE
Typo titlename...

### ISSUE THREAD

**Issue by adramalech** [Kikobeats/uno-zen#1]
Hey was just letting you know in your social.hbs file from master:

```
<a target="blank" href="https://github.com/Kikobeats" title="Kikobeats on Twitter">
```

shouldn't the title be "Kikobeats on Github?

**Comment by Kikobeats** [comment]
Thanks, I fixed!

I want to use a better way to integrate with Ghost API for reference the user of the blog instead of "Kikobeats" and edit manually. Any idea?
