### ISSUE TITLE
How can I change the animation ? 

### ISSUE THREAD

**Issue by waqaskhan137** [Kikobeats/uno-zen#10]
Hello, 
I want to change the animation You have used (you click on Blog and it slide back). 
How do I change it?
Thanks,

**Comment by Kikobeats** [comment]
nice question

**Comment by ranawaqas-ai** [comment]
So, you have any suggestion ?

**Comment by Kikobeats** [comment]
@waqaskhan137 not really, I feel good with the animation and is very specific for make a easy change :-(

**Comment by ranawaqas-ai** [comment]
If you know how to do it but you don't have time. Please let me know where and which file I have to change.

**Comment by boredstiff** [comment]
In case you never figured it out, it's inside of main.coffee - the script is hosted on a server. 
You can just substitute it. 

https://nthitz.github.io/turndownforwhatjs/tdfw.js

@Kikobeats Really?
@waqaskhan137 I hope this helps you.

**Comment by Kikobeats** [comment]
@alexwidener tdfw file is for 404 animation, not for aside animation.

If you want to change the aside animation you need to edit the css code.

The purpose of this theme is not be a super customizable theme. Use it as blog boilerplate and adapt all that you need, like colors, animation, etc
