### ISSUE TITLE
500px Icon not appearing in sidebar - edit: resolved

### ISSUE THREAD

**Issue by theodorp** [Kikobeats/uno-zen#100]
edit: mistake made on my part.

~~I'm not able to get the 500px icon to appear in my sidebar, there is a link that goes to my 500px account, but no icon. See attached image.~~

~~note: you can't see it in the screen shot, but I'm moused over where the 500px icon should be.~~
![screen shot 2015-10-07 at 3 45 35 pm](https://cloud.githubusercontent.com/assets/7495153/10349058/95e3e722-6d0a-11e5-8e61-573aa659c661.png)

**Comment by foorb** [comment]
Maybe it's me, but I don't understand the problem or rather have not enought information.
Can you provide an excerpt from the source and a link to your website?

**Comment by foorb** [comment]
Ah...it's linked in your profile. I have a look at it.

**Comment by foorb** [comment]
This works fine for me:

``` html
<li class="social item hvr-grow-rotate">
    <a rel="me" target="blank" href="https://500px.com/theodorr" title="Theodorr on 500px">
      <i class='icon icon-social-500px'></i>
      <span class="label">500px</span>
    </a>
</li>
```

**Comment by theodorp** [comment]
Ah, I see my error now. The icon is appearing now. 

I'll remove this issue, thanks for your help!

**Comment by foorb** [comment]
nice to hear :)
You don't have to remove the issue. I think it is not even possible. 
Just close the issue

**Comment by Kikobeats** [comment]
Yeah!
