### ISSUE TITLE
Code formatting Flicker

### ISSUE THREAD

**Issue by foorb** [Kikobeats/uno-zen#102]
When I hover/mouseover over code formatting, the code begins to flicker:

![okt 10 2015 22 40](https://cloud.githubusercontent.com/assets/14993807/10413174/156f2460-6fa0-11e5-8bc9-ab60c37ee62b.gif)

In the default theme this problem doesn't appear. Is it wanted? It doesen't feel smooth.
Any ideas?

**Comment by Kikobeats** [comment]
it's a partial bug. The idea is show in black color when mouse is over in the code box, but currently the effect is applied in the text 😂.

Could you make a PR of this?

**Comment by foorb** [comment]
I'm not that good in CSS.
I think I can't do that.

**Comment by Kikobeats** [comment]
I improved code style un `2.6.0` using prismjs, you can view a preview in the [styleguide post view](http://kikobeats.com/styleguide/).

You can download the pre-release version as well, soon the final version!
