### ISSUE TITLE
Somethings wrong with Twitter share

### ISSUE THREAD

**Issue by foorb** [Kikobeats/uno-zen#108]
Twitter share doesn't seem to work properly:
![bildschirmfoto vom 2015-10-12 20-05-55](https://cloud.githubusercontent.com/assets/14993807/10434909/c3c25eba-711c-11e5-9a8a-bc27f1cd7c91.png)

Submitted URL is:
https://twitter.com/intent/tweet?text=Welcome%20to%20Ghost%20%EF%BF%BD&url=&hashtags=Getting%20Started&original_referer=

**Comment by Kikobeats** [comment]
the strange character is '»'. Can you confirm me that, if you change [line 19 of post.hbs](https://github.com/Kikobeats/uno-zen/blob/master/post.hbs#L19) for this, works?

``` hbs
href="javascript:window.open('http://twitter.com/share?hashtags={{tags separator="," autolink="false"}}&text={{title}} {{encode '»'}} ', '_blank', 'width=400,height=500');void(0);">
```

**Comment by foorb** [comment]
Not only I think. Somethings seems to be wrong with the url and hashtags too

``` html
 <a alt="Tweet '{{title}}'" href="https://twitter.com/intent/tweet?text={{encode title}} {{encode ' » '}}&amp;url={{url absolute="true"}}" >
```

This worked for me

**Comment by Kikobeats** [comment]
available in the next release :-)

**Comment by foorb** [comment]
:thumbsup:

**Comment by RReverser** [comment]
So I found this issue trying to figure out why `»` is always appended to the end of the tweet so all the generated tweets look like `Here Goes Post Title » https://url.com/ #hashtags`, and it sounds like it was added intentionally these few years ago? What was the reason for the closing quote without opening one?

**Comment by Kikobeats** [comment]
@RReverser yes, I was added intentionally:

https://github.com/Kikobeats/uno-zen/blob/4cac42ab74fdb4b7ade39ba02f620fc3c250ccf4/page.hbs#L7

If you make a PR I'm happy to remove it 😄

**Comment by RReverser** [comment]
@Kikobeats Done: https://github.com/Kikobeats/uno-zen/pull/240
