### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by elwadi** [Kikobeats/uno-zen#115]
The URL of my blog is:  elwadi.me

**Comment by foorb** [comment]
Probably you should do some more styling first?
Like the favicon and social links. 
There is nothing individual with his blog, the images except for times.
More information how you do this you can find [here](https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md)

**Comment by Kikobeats** [comment]
not opposite, but I prefer show posts in your blogs before add it to be sure that you going to use the theme (and a little more customization as @foorb says you).

When you experiment more with your blog, feel free to open a new issue!
