### ISSUE TITLE
No styling applied to footnotes

### ISSUE THREAD

**Issue by jloh** [Kikobeats/uno-zen#116]
There isn't any special styling done to Footnotes which can be done as per the docs [here](http://support.ghost.org/markdown-guide/#footnotes).

Footnotes get placed in `<sup>` tags like this:

``` html
<sup id="fnref:1"><a href="#fn:1" rel="footnote">1</a></sup>
```

The only styling that Casper (as a base example) seems to do to them is align them a little higher:

``` css
sup {
    top: -0.5em;
}
```

What this means it that it just looks like a normal link to the character `1`.

I don't know how Casper does it, but it also wraps the footnotes themselves into some funky markup (I added a bit of formatting to make it easier to read):

``` html
<div class="footnotes">
  <ol>
    <li class="footnote" id="fn:1">
      <p>
        Some random footnote text. <a href="#fnref:1" title="return to article">↩</a>
      </p>
    </li>
  </ol>
</div
```

**Comment by Kikobeats** [comment]
It's true, because this projects starts as my personal blog theme and I don't use footnotes when I write a post 😁.

Do you think that you can convert this into a PR?

To know how Casper style the footnotes simply change your local ghost theme and inspect the CSS!

**Comment by jloh** [comment]
Yeah I'm trying to get the dev environment going now but I can't seem to get past the bower install

```
[09:46:22] 1 $ bower install
bower                           ENOENT No bower.json present
```

**Comment by Kikobeats** [comment]
strange because the file exists: https://github.com/Kikobeats/uno-zen/blob/master/bower.json

the current path of your terminal is correct?

**Comment by Kikobeats** [comment]
@Mooash can you say me the status of this? :-)

**Comment by jloh** [comment]
Hey, I managed to get it working but still working on the styling and all that. Happy for you to close this and I'll submit a PR when its ready.

**Comment by Kikobeats** [comment]
:+1:
