### ISSUE TITLE
Add detail README.md

### ISSUE THREAD

**Issue by jeanlucaslima** [Kikobeats/uno-zen#117]
You need to restart ghost for the theme appear on the blog.

**Comment by Kikobeats** [comment]
Can you create a PR of this? Just 1 minute!

**Comment by Kikobeats** [comment]
Actually is not a bug of the blog because is a general behavior with whatever ghost blog....

**Comment by jeanlucaslima** [comment]
Yeah! It's not a bug, just an installation note. I'll PR. Thanks.
