### ISSUE TITLE
Open localhost tab when clicking "blog" button

### ISSUE THREAD

**Issue by jeanlucaslima** [Kikobeats/uno-zen#119]
Hi, I've just installed and followed all steps on README.md and on DOCUMENTATION.md. When I click the "blog" button, it also open "http://localhost:2368/#open" tab and loads the blog. 

This was observed on Google Chrome v46.0.2490.71; OS: Linux; (normal and incognito tabs)
Also observed on Firefox 41.0.2; OS: Linux; and if you access directly a post on mobile version. 

This is **not** observed on mobile version, for Google Chrome for Android latest version, on the home page.

Here's where this behavior is happening: on front page: http://jeanlucaslima.com/ and this post to reproduce on mobile: http://jeanlucaslima.com/welcome-to-ghost/

**Comment by jeanlucaslima** [comment]
Probably there's some configuration I'm missing.

**Comment by jeanlucaslima** [comment]
![ghost](https://cloud.githubusercontent.com/assets/1311402/10617726/b94c61ea-774a-11e5-931a-b8a06a00e0d3.gif)

**Comment by foorb** [comment]
Hey,
you need to change the url in your ghost configuration (`ghost/config.js`) from `localhost:2368` to `jeanlucaslima.com`

**Comment by foorb** [comment]
And make sure you run you ghost with `--production` or `NODE_ENV=production`

**Comment by jeanlucaslima** [comment]
@foorb I am running with NODE_ENV=production, and here's ghost/config.js:

```
config = {
    // ### Production
    // When running Ghost in the wild, use the production environment.
    // Configure your URL and mail settings here
    production: {
        url: 'http://jeanlucaslima.com',
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '0.0.0.0',
            port: '2368'
        }
    },
```

**Comment by jeanlucaslima** [comment]
@foorb I reinstalled, looks like it was a problem with forever checking if it was a production environment.

**Comment by foorb** [comment]
:+1:

**Comment by Kikobeats** [comment]
@foorb You looks like Uno Zen collaborator! good job :-)
