### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by javierescobare** [Kikobeats/uno-zen#121]
The URL of my blog is: http://escobarjavier.azurewebsites.net/. I'm just fixing the Disqus section :D.

**Comment by Kikobeats** [comment]
doesn't work D:

**Comment by javierescobare** [comment]
Sí funciona D: qué raro 
![screenshot 118](https://cloud.githubusercontent.com/assets/15280278/11171841/6e0f4dcc-8bc8-11e5-913b-42f4577edb0f.png)

**Comment by Kikobeats** [comment]
```
$ ping http://escobarjavier.azurewebsites.net
ping: cannot resolve http://escobarjavier.azurewebsites.net: Unknown host
```
