### ISSUE TITLE
Code Injection doesnt work?

### ISSUE THREAD

**Issue by Zenuncl** [Kikobeats/uno-zen#128]
<pre><code>
var ga_id = 'UA-YOUR_ID_HERE';
var disqus_shortname = '';
var profile_title = '';
var profile_resume ='';
</code></pre>

I tried to use this in Code Injection Head to customer the function, such as disqus. However, none of this works on my computer. Why??

**Comment by Kikobeats** [comment]
First you need to create a Disqus account and setup the shortname. Did you
do it?

**Comment by Zenuncl** [comment]
I already fixed it. I think its because the code injection somehow does not work in the 1st place. I reinstall the ghost and themes. Everything works fine now.

Thank you for the awsome themes
