### ISSUE TITLE
Content Security Policy violations

### ISSUE THREAD

**Issue by guimochila** [Kikobeats/uno-zen#129]
Hi there,

I can't get the theme to work in my personal server, I get the following error when trying to load the page:

> Content Security Policy: The page's settings blocked the loading of a resource at https://www.google-analytics.com/analytics.js ("script-src https://guimochila.io 'unsafe-inline' 'unsafe-eval' https://ssl.google-analytics.com https://assets.zendesk.com https://connect.facebook.net"). <unknown>
> 
> Content Security Policy: The page's settings blocked the loading of a resource at https://code.jquery.com/jquery-1.11.3.min.js ("script-src https://guimochila.io 'unsafe-inline' 'unsafe-eval' https://ssl.google-analytics.com https://assets.zendesk.com https://connect.facebook.net"). <unknown>
> 
> Content Security Policy: The page's settings blocked the loading of a resource at https://fonts.gstatic.com/s/raleway/v9/QAUlVt1jXOgQavlW5wEfxQLUuEpTyoUstqEm5AMlJo4.woff2 ("font-src https://guimochila.io https://themes.googleusercontent.com"). <unknown>

You can try https://guimochila.io

I'm not sure what it is happening. 

Thank you.

**Comment by guimochila** [comment]
I have found the issue, it was on the server-side. Thank you.

**Comment by jloh** [comment]
What is your URL configured in Ghost out of curiosty? Looking at your blog I have a feeling its `http://guimochila.io/` instead of `https://guimochila.io/` (note the second one is `https` instead of `http`)

**Comment by guimochila** [comment]
I checked and it was configured as `http`and not `https`, also there was security line configuration in my nginx.conf file which was blocking external scripts to be loaded.
