### ISSUE TITLE
No cover page option ?

### ISSUE THREAD

**Issue by gmolveau** [Kikobeats/uno-zen#130]
Hello :)
I love your theme ! 
I'd like to know if it was possible to desactivate the cover page and directly go to #open page when going on the blog ?

Thank you for your answer ! :)

**Comment by Kikobeats** [comment]
Just redirect your blog to /#open. No more custom way to do it, just simple
:-)

**Comment by gmolveau** [comment]
:) thank you for your answer !

**Comment by krestjaninoff** [comment]
@Kikobeats Hi! I have the same problem: my site is xyz.com and I want to refer/share it as xyz.com, not xyz.com/#open :( May be there is a code (the same one that triggers on /#open anchor click) which can be added to the Code Injection section of the Admin console?

**Comment by Kikobeats** [comment]
not possible!
