### ISSUE TITLE
Failed to lookup view index in views directory

### ISSUE THREAD

**Issue by julianonunes** [Kikobeats/uno-zen#133]
I just installed Uno-zen using the instructions in the readme file and I'm getting this error "failed to lookup view index in views directory". 

I'm running Ghost 0.7 on Heroku.

**Comment by Kikobeats** [comment]
try to restart Ghost node process because need to statically load the theme

**Comment by julianonunes** [comment]
I tried restarting Dynos on Heroku without success. Shouldn't it work?

**Comment by Kikobeats** [comment]
my recommendations are more for local development, I don't have idea about your production scenario, I'm sorry!

**Comment by julianonunes** [comment]
No problem, I'll keep trying here. Thanks anyway.

**Comment by Zacaria** [comment]
it looks like the .git folder of the theme bothers when you push on remote server (for me openshift)
So the server does receive the uno-zen folder with nothing inside
