### ISSUE TITLE
Dependency issues - NodeJS v0.10

### ISSUE THREAD

**Issue by Skowt** [Kikobeats/uno-zen#134]
I've just resolved issues with my own version of uno-zen where using the same NodeJS version as recommended by Ghost (v0.10) broke the development version of uno-zen.

The fix was simply:
- Updating package.json:
  Add 'es6-promise' as a dependency. Version is just set as *.
- Update gulpfile.coffee:
  Add 'require('es6-promise').polyfill();' on the line before 'prefix      = require 'gulp-autoprefixer''.

Once these two changes are made, run 'npm install' and then you can use gulp once again.

I prefer doing this so I can stick to one version of NodeJS rather than jumping between the two for the blog and the theme.

**Comment by Kikobeats** [comment]
The engines recommended by Ghost are:

```
{
  "node": "~0.10.0 || ~0.12.0",
  "iojs": "~1.2.0"
}
```

But is different the node version necessary to run the Ghost server that the node version necessary for run the development scenario (like compile assets).

Particularly, I use `0.12.7` in the development and production scenario.

Instead of add two dependencies and make the build higher, I prefer that you update your node version. I'm going to add a `.node-version` file that automatically change your current node version to be the exact necessary.

Also I'm going to add a badge in the repository :-)

**Comment by Kikobeats** [comment]
Also if you check the package.json of the proyect the node version is correctly stablished!

**Comment by Skowt** [comment]
Hey Kikobeats,

I see this is the case. The reason I pointed this out was due to the _official_ Ghost installation guide recommending NodeJS v0.10. 

If you review here: https://github.com/tryghost/Ghost

> Make sure you've installed Node.js - We recommend the latest Node v0.10.x release.
> 
> Ghost is also compatible with Node v0.12 and io.js v1.2, but please note that these versions are more likely to run into installation problems. May contain nuts.

This is why I proposed to go with nodejs v0.10 but this was just something I thought I should make you aware of. I know there will be a lot of Developers who would want to stick with the recommended version but as this is your theme, you have final say.

No disrespect towards you or your work. I know it is a brilliant theme which I personally utilize. :+1:

**Comment by Kikobeats** [comment]
good point!

**Comment by Skowt** [comment]
Just to clarify, this is an issue I'm bringing up because I had a lot of issues trying to get everything running but once I managed to find that dependency and also realize the issue was the versioning, I was able to get the theme up and running.

I must say my website is looking absolutely awesome with the theme you made. Thanks again :+1:  :)
