### ISSUE TITLE
Code Highlighting not working

### ISSUE THREAD

**Issue by Skowt** [Kikobeats/uno-zen#138]
I'm unable to proper add blocks of code to my blog posts since the latest update and when I do, there is no highlighting as what Prism should provide.

Can you assist me with resolving this?

Test URL: http://danielpietersen.com/ghost-blog-apache-nginx-cloudflare/

**Comment by jloh** [comment]
Your blocks of code appear fine for me, it seems you've just lost some syntax highlighting maybe?

**Comment by Skowt** [comment]
Agreed.

The middle block also doesn't show the label although it's supposed to be PHP. I've listed it like I have the others, so I'm not sure where I'm going wrong.

**Comment by jloh** [comment]
The Prism.js highlighting included within Uno-Zen doesn't include highlighting for PHP I'm afraid.

Only markup, css, clike, javascript, bash, c, coffescript, git, markdown, scss and sql.

```
http://prismjs.com/download.html?themes=prism-okaidia&languages=markup+css+clike+javascript+bash+c+coffeescript+css-extras+git+markdown+scss+sql&plugins=line-numbers+autolinker+show-language
```

**Comment by Kikobeats** [comment]
Hi!

[PHP syntax is not supported by default](https://github.com/Kikobeats/uno-zen/blob/master/assets/scss/modules/_prism.scss#L1) to prevent a too much bigger asset file. Just support the most standalone languages (and coffeescript :P).

But you can:

1) go to prismjs.com,
2) generate your custom highlight code
3) paste in the file
3) compile the assets

I have to extend documentation for support this new use case. If you do the process, please, make a PR to make more easy reproduce the steps for other user.

**Comment by Skowt** [comment]
Awesome, Thanks Kiko
