### ISSUE TITLE
Code blocks without a language lose styling

### ISSUE THREAD

**Issue by jloh** [Kikobeats/uno-zen#139]
At first I thought it was just an issue with my blog, but you can see this on yours here as well http://kikobeats.com/road-to-javascript-4/

Seems that by removing the initial uno-zen code block CSS prism.js isn't applying to those without a language.

**Comment by Kikobeats** [comment]
Fixed in `2.6.1` :+1:

**Comment by jloh** [comment]
Damn, I'm trying to use my own version of prism.js which includes different plugins to yours which seems to be causing the problem. Do you have any idea? You can see 2.6.1 live [here](https://www.mooash.me/2015/08/13/pipe-nsca-logs-to-separate-file/) with the issue.

**Comment by Kikobeats** [comment]
Look my css for prism. You need to remove code language selector for works
for all pretty code blocks
