### ISSUE TITLE
The blog title did not load dynamicly

### ISSUE THREAD

**Issue by Pana** [Kikobeats/uno-zen#14]
FYI

**Comment by Kikobeats** [comment]
can you explain better the issue?

**Comment by Pana** [comment]
For example my blog name is Pana and the main header  in page is still your name kikobeats

**Comment by Kikobeats** [comment]
You need to change manually in the `partials/aside.hbs`. If you detect that is possible to setup it using the Ghost API for build themes, please make a PR of this :-)
