### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by huytd** [Kikobeats/uno-zen#145]
The URL of my blog is: http://huytd.github.io/

Screenshot

![](http://i.imgur.com/896fITW.png)

**Comment by Kikobeats** [comment]
Until now it was adding the blogs manually one by one. I've created a process to add your blog in the showcase. Can you follow it? I would appreciate 🙂

https://github.com/Kikobeats/uno-zen/blob/master/SHOWCASE.md#add-your-blog
