### ISSUE TITLE
Typo in "Writtings", should only contain one 't'.

### ISSUE THREAD

**Issue by devilleweppenaar** [Kikobeats/uno-zen#151]
When viewing the author page, the heading "Writtings" is misspelled and should only contain one 't'. See screenshot below, or view [this page from my blog](https://devillex.com/author/deville/).

<img width="597" alt="screen shot 2015-12-28 at 1 22 26 pm" src="https://cloud.githubusercontent.com/assets/11049609/12017996/2eaac43a-ad66-11e5-86bd-b6dac60cf559.png">

**Comment by Kikobeats** [comment]
thanks! available in the next tagged version (waiting for something more, but available today)

**Comment by devilleweppenaar** [comment]
Cool. Thanks for the prompt response and awesome theme!
