### ISSUE TITLE
make post images width: auto and max-width: 100%

### ISSUE THREAD

**Issue by floryn90** [Kikobeats/uno-zen#153]
it will me nice if will be possible to have post's images auto-width and max-width to 100%

**Comment by Kikobeats** [comment]
Why could be nice?
What is the problem?
What are you trying to fix?
Can you upload a image explaining your point of view?

:)

**Comment by floryn90** [comment]
if you go to my blog (www.florinlungu.it) and open the first article for example, you will see some screen-shots of my phone and the visualization is not optimal. if i set the style of images to with:auto and max-width: 100% the image is shown correctly and not zoomed in.

**Comment by Kikobeats** [comment]
I see perfect in my iPad 

But if you think that you have the solution, what about create a PR?

**Comment by Kikobeats** [comment]
@floryn90 I'm trying to put attention to this but I don't see the difference betwenn:

```
/* current */
width: 100%;
```

and

```
/* proposal */
width: auto;
max-width: 100%;
```

Can you post images of your visualization of both?

**Comment by floryn90** [comment]
full-width: http://pasteboard.co/qinQXpj.png
fixed-width: http://pasteboard.co/qixsu63.png

**Comment by Kikobeats** [comment]
My fail. I thought all the time that you said mobile version 😆.

I'm preparing the next version that will be available tonight!
