### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by Ekt0s** [Kikobeats/uno-zen#155]
The URL of my blog is:  louis-gabriel.io 

Thanks for the great work !

**Comment by Kikobeats** [comment]
Until now it was adding the blogs manually one by one. I've created a process to add your blog in the showcase. Can you follow it? I would appreciate 🙂

https://github.com/Kikobeats/uno-zen/blob/master/SHOWCASE.md#add-your-blog
