### ISSUE TITLE
Script suggestion: package theme for usage on Ghost(Pro)

### ISSUE THREAD

**Issue by devilleweppenaar** [Kikobeats/uno-zen#156]
I recently migrated my blog from self-managed to Ghost(Pro). The ReadMe instructions worked great when I managed the host, but for Ghost(Pro) you need to upload custom themes as a *.zip archive. I've done this manually a couple of times, but found it to be a bit tedious. To help simplify the process I created a script that packages everything that is needed (I think :) ).

The script is available in my repo ([devillex/uno-zen](https://github.com/devillex/uno-zen/blob/master/scripts/package.sh)), but looks like this:

``` bash
#!/bin/bash

FILES="*.hbs *.md *.html partials/ assets/js/uno-zen.js assets/css/uno-zen.css assets/fonts/ assets/img/"
OUTPUT="uno-zen"

if [ $# -eq 0 ]; then
    echo No argument supplied, using default as archive name.
else
    echo Argument supplied, using that as archive name.
    OUTPUT=$1
fi

echo Using $OUTPUT as archive name.

if [ -f "$OUTPUT.zip" ]; then
    echo Output file $OUTPUT.zip already exists, removing old version.
    rm $OUTPUT.zip
    echo Old version removed.
fi

echo Creating archive.

zip -r $OUTPUT $FILES

echo Done!
```

If you agree that this script may help other users as well, I'd like to suggest that it is included in the _scripts_ folder of this repo.

Also, please verify that I include all of the required files in the archive. For instance, I wasn't sure if the 'assets/vendor' folder created during the build process was required, as it significantly increases the archive size.

**Comment by Kikobeats** [comment]
yeah, of course, add it to the project!

I think that `build.sh` could be a good nice :-)

Waiting your PR!
