### ISSUE TITLE
Problem with 2.6.9

### ISSUE THREAD

**Issue by skitoo** [Kikobeats/uno-zen#160]
Hi,

I installed the latest version of your theme but it doesn't really work.
I have many problems :
- The #open animation does'nt work
- Syntax highlighting does not work

I have followed the install documentation. I have added jquery on footer.

You can show my blog at the following url : http://blog.skitoo.net

(I use Firefox)

Thank you

**Comment by skitoo** [comment]
#open animation doesn't work on "Journal" button

**Comment by Kikobeats** [comment]
about open button, you have to specify the DOM selector, read this:
https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#open-button

about highlighting: Python is not supported by default, read this:
https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#highlight-code-support

**Comment by skitoo** [comment]
Ok thank you !

**Comment by Kikobeats** [comment]
feel free to reopen if you need something :-)
