### ISSUE TITLE
CSS Color

### ISSUE THREAD

**Issue by foorb** [Kikobeats/uno-zen#165]
Hey,
I am not familiar with css or even scss. Where can i find the colors? The underlined and the hover:
![2016-01-07 18_16_30-kikobeats](https://cloud.githubusercontent.com/assets/14993807/12177109/d7a6410c-b56a-11e5-8556-7d1b3e0cb759.png)

**Comment by Kikobeats** [comment]
check here: https://github.com/Kikobeats/uno-zen/blob/master/assets/scss/modules/_variables.scss

then exec `gulp build` to compile, or just run `gulp` to automatically execute under each change.

If you have more question feel free to post here!

**Comment by foorb** [comment]
Ah...thanks a lot!
