### ISSUE TITLE
Make title on default template customizable

### ISSUE THREAD

**Issue by waja** [Kikobeats/uno-zen#166]
Looking into https://github.com/Kikobeats/uno-zen/blob/570d08c8dd1bedba0912288c1dccb6f547713cb7/index.hbs#L3 indicates that the headline of the index is fixed.
Adjusting of the Profile title is supported like documented in https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#profile-title. Maybe also the headline of the index can be made configurable this way.

**Comment by Kikobeats** [comment]
Good idea! :+1: 

Could you convert this issue into PR? 

A little checklist to implement it:
- [ ] Assign a namespace for this and check it in the [init](https://github.com/Kikobeats/uno-zen/blob/master/assets/js/src/__init.coffee#L43).
- [ ] Add Documentation section.
