### ISSUE TITLE
Excerpts on Index page

### ISSUE THREAD

**Issue by waja** [Kikobeats/uno-zen#167]
In the past (older versions) on the index page there was shown experts of the posts. In newer versions only the headlines are listed.
I reverted (https://github.com/waja/uno-zen/commit/cfdccc7596fbd897cb3703cf8fbc37987fa974b2) this in my branch but maybe it would be cool to have that configurable.

Thank might be possible be possible via script value?

**Comment by Kikobeats** [comment]
Actually I feel confortable with the current approach. I prefer focus in a good that a random snippet of text. 

Thanks for think in this!
