### ISSUE TITLE
Cannot get discuss working

### ISSUE THREAD

**Issue by dsbatman** [Kikobeats/uno-zen#170]
Hi Kiko, 

I can't get the disqus working after installing this theme.

```
<script>
var disqus_shortname = 'shanux.disqus.com';
</script>
```

Is there anything we have to do, other than this. This is the registered shortname from disqus.com

My Domain: shanux.com

**Comment by Kikobeats** [comment]
You have to configure your disqus shortname in the disqus panel, just be a one word, like `shanux`, not an url.
