### ISSUE TITLE
Problem about animation

### ISSUE THREAD

**Issue by Lyken17** [Kikobeats/uno-zen#174]
I installed your theme on my ghost blog. However, I found one strange thing. 
Transform animation works normally when I click avatars picture, but it doesn't work when click 'Post Icon'. Both elements have a "href = http://lykensyu.com/#open" attribute. 

Browser : Safari

**Comment by Lyken17** [comment]
my site : http://lykensyu.com/

After clicking 'Post Icon', I need to refresh page, then it will work.

**Comment by Lyken17** [comment]
I've fixed it by doing follow:

edit `/themes/uno-zen/partials/navigation.hbs` and add  id="avatar-link"  to navigation elements'

Before 

``` html
<li class="nav-home nav-current nav-current">
        <a href="http://lykensyu.com/">Post</a>
</li>
```

After 

``` html
<li id="avatar-link" class="nav-post nav-current">
        <a href="http://lykensyu.com/#open">Post</a>
</li>
```

Since not familiar with js & coffee, I can't fix it in a proper way. I read source code in `/uno-zen/assets/js/src`, and found a event related with `id = avatar-link`. Then diff the uno-zen.js file in your blog and my blog, perhaps there should be one more rule for navigation?

PS: After doing this, other navigations can't work as expect in some situations...

**Comment by Lyken17** [comment]
Ok... I finally figure it out. There is a special css rule for `nav-Posts`, so only need to change `Post` button to `Posts`, and everything works well.

The special rule was declared in `uno-zen/assets/js/src/__init.coffee  line 47`. If you could declare it in document, that would be great.

**Comment by Kikobeats** [comment]
Read documentation https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#open-button
