### ISSUE TITLE
CodePen for Social Icon missing?

### ISSUE THREAD

**Issue by Salvero** [Kikobeats/uno-zen#181]
Hi,

I want to know why we don't have social-icon for **CodePen**?

> Here is a full list of social network classes that you can use:
>     icon-social-500px
>     icon-social-behance
>     icon-social-delicious
>     icon-social-designer-news
>     icon-social-deviant-art
>     icon-social-digg
>     icon-social-dribbble
>     icon-social-facebook
>     icon-social-flickr
>     icon-social-forrst
>     icon-social-foursquare
>     icon-social-github
>     icon-social-google-plus
>     icon-social-hi5
>     icon-social-instagram
>     icon-social-lastfm
>     icon-social-linkedin
>     icon-social-medium
>     icon-social-myspace
>     icon-social-path
>     icon-social-pinterest
>     icon-social-rdio
>     icon-social-reddit
>     icon-social-skype
>     icon-social-spotify
>     icon-social-stack-overflow
>     icon-social-steam
>     icon-social-stumbleupon
>     icon-social-treehouse
>     icon-social-tumblr
>     icon-social-twitter
>     icon-social-vimeo
>     icon-social-xbox
>     icon-social-yelp
>     icon-social-youtube
>     icon-social-zerply
>     icon-mail

Thanks,
Salman

**Comment by Kikobeats** [comment]
Feel free to add it and make a PR

**Comment by Salvero** [comment]
Thanks, it is fixed now! 

:+1:

**Comment by waja** [comment]
@Salvero how was it fixed?

**Comment by Salvero** [comment]
@waja 

Here's how it worked:

Just go to this Ionicons site - http://ionicons.com/ to download both css/fonts and move them into your Assets folder. 

Make sure you links files in **default.hbs**:

```
    <link rel="stylesheet" type="text/css" href="{{asset "css/ionicons.min.css"}}" />
    <link rel="stylesheet" type="text/css" href="{{asset "css/ionicons.css"}}" />
```

Then check with **social.hbs** under partials folder to add new class for CodePen:

```
  <li class="social item hvr-grow-rotate">
    <a rel="me" target="blank" href="http://codepen.io" title="CodePen">
      <i class='icon ion-social-codepen-outline'></i>
      <span class="label">CodePen</span>
    </a>
  </li>
```

Hope that helps :)
