### ISSUE TITLE
Mobile Display Hiccup

### ISSUE THREAD

**Issue by nacho693** [Kikobeats/uno-zen#182]
Hello, first, thanks for the awesome theme.  I just updated from Ghost 6.4 to 7.8 and your theme correspondingly on http://ajr.io.  However, it's not showing very mobile friendly on my Samsung Note 4
![screenshot_2016-03-06-22-00-27](https://cloud.githubusercontent.com/assets/10793124/13561043/4ee2e53a-e3ed-11e5-9dc7-253f685d06e4.png)
.

**Comment by Kikobeats** [comment]
See devtools console, looks like is not loading the js/css assets files

**Comment by nacho693** [comment]
Cache issue.  Using openshift, used: gear restart

Thanks again for the awesomeness!
