### ISSUE TITLE
change the  favicon

### ISSUE THREAD

**Issue by ghost** [Kikobeats/uno-zen#185]
Hey, I'm using your Ghost blog theme.I have a question.How to change a favicon on my Ghost blog?
I can't get this problem. Looking forward to your reply. Thanks.

**Comment by Kikobeats** [comment]
Read the documentation 😅

**Comment by ghost** [comment]
Hey Kiko! Thanks. I solved it following the documentation. But it didn't
change. Now it just become effective. That's a network question 😅
I'm so stupid!😅
Thank you, Kiko.

2016-03-17 17:03 GMT+08:00 Kiko Beats notifications@github.com:

**Comment by Kikobeats** [comment]
haha no problem! 😁
