### ISSUE TITLE
function ReadingTime is called on the Posts page but doesn't exist

### ISSUE THREAD

**Issue by Windyo** [Kikobeats/uno-zen#186]
# Issue

When loading a post, the text "read" is shown. On the backend, the function "readingTime" is called ; this function is a part of uno-urban and not a part of uno-zen
# Collateral Damage

Any script depending on correct js execution stops (the updated GhostHunter Search for example)
# Suggested fix

Remove the reference to the readingTime function, if it is to be a premium feature.

**Comment by Kikobeats** [comment]
Hmm not really, this feature exists in this version, but yes, looks that something is broken. Let me check

**Comment by Kikobeats** [comment]
@Windyo did you try with the last version in `master` branch instead of the tag versrion?

I think that works fine, I can release a new patch version. Please, confirm me.

**Comment by Windyo** [comment]
@Kikobeats I basically just did $ curl -sSL http://git.io/vcIHr | sh. 
Just ran update.sh, problem still persists.

**Comment by Kikobeats** [comment]
I think that is a little bug only present in the last version.

BTW I fixed another little bug, so I'm going to release a new version

If the problem persist, feel free to comment here about that.

**Comment by Windyo** [comment]
Okay perfect. thanks for the information =)

**Comment by Kikobeats** [comment]
New release `2.7.8`, try it!

Also try with a fresh installation. Maybe is a bug of the script process.

**Comment by Windyo** [comment]
the update script seems to stall if you do any customization on the theme. I'll just redownload the whole thing ;)

**Comment by Windyo** [comment]
All clear, everything work !just have to get my customizations back. Thnks for the help and the quick answer !

**Comment by Kikobeats** [comment]
You're welcome 😀

**Comment by Windyo** [comment]
Oh and by-the-by : I'm looking for people who tried Ghosthunter before to see if in its current state the API function could be used by people with 'bigger' blogs.

If you have a few minutes of free time to try my fork and see if performance-wise it holds up that would be much appreciated ;)

**Comment by Kikobeats** [comment]
GhostHunter looks deprecated until Ghost releases plugins integration.

I remove it in Uno Urban and I'm using Google search instead, and works fine.

**Comment by Windyo** [comment]
the Ghost Team actually released their API ;) thanks and have a nice Sunday !

**Comment by Kikobeats** [comment]
Really? Give me moar info :-)

On Sunday, 20 March 2016, G notifications@github.com wrote:

> the Ghost Team actually released their API ;) thanks and have a nice
> Sunday !
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/Kikobeats/uno-zen/issues/186#issuecomment-198889051

## 

_Att, Kiko._

**Comment by Windyo** [comment]
Well the Ghost team has opened their API in pubic beta, see the doc ([here](http://api.ghost.org/v0.1/docs)).

I think the main ghosthunter repo is dead so I forked it and made it compatible with the api [here](https://github.com/Windyo/ghostHunter)

There are some kinks to iron out but normally everything is a-ok.

**Comment by Kikobeats** [comment]
Awesome! Consider create a PR integrating your work. I hope that I could
use it on my rest of projects :-)

On Sunday, 20 March 2016, G notifications@github.com wrote:

> Well the Ghost team has opened their API in pubic beta, see the doc (here
> http://api.ghost.org/v0.1/docs).
> 
> I think the main ghosthunter repo is dead so I forked it and made it
> compatible with the api here https://github.com/Windyo/ghostHunter
> 
> There are some kinks to iron out but normally everything is a-ok.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/Kikobeats/uno-zen/issues/186#issuecomment-198944130

## 

_Att, Kiko._

**Comment by Windyo** [comment]
already did a PR but some PRs have been waiting for over a year so I'm not sure the owner checks his projects. 

Anyhow if you decide to test the api version of ghosthunter drop me a line., I'll try and maintain the project a bit.

**Comment by Kikobeats** [comment]
I recommend you create your own project and go ahead

On Sunday, 20 March 2016, G notifications@github.com wrote:

> already did a PR but some PRs have been waiting for over a year o I'm not
> sure the owner checks his projects.
> 
> Anyhow if you decide to test the api version of ghosthunter drop me a
> line., I'll try and maintain the project a bit.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/Kikobeats/uno-zen/issues/186#issuecomment-198946838

## 

_Att, Kiko._
