### ISSUE TITLE
Have a one page version on mobile

### ISSUE THREAD

**Issue by stylersnico** [Kikobeats/uno-zen#187]
Hi,

I want to use uno-zen for a one page resume and I want the same view we have on desktop on mobile.
I don't want to have the post since I don't use them.

Is this possible ? :)

Thanks,
BR

**Comment by Kikobeats** [comment]
sure!

Check javascript source files to see how mobile or desktop version is determinate and edit it as your convenience.

Feel free to reply this comment although I close the issue :)

**Comment by stylersnico** [comment]
Hi,
I've taken another theme for my main website which fits more what I need but I will use uno zen for my blog :)

Thanks for the prompt answer :+1:

**Comment by Kikobeats** [comment]
sweet! 😀
