### ISSUE TITLE
Git won't track the theme

### ISSUE THREAD

**Issue by Huanzhang89** [Kikobeats/uno-zen#188]
I have tried to install the theme using the bash command provide in the ReadMe file and for the love of god git won't track the theme (due to the theme being a sub repository, containing a .git folder). 

The only way to get around the problem is to:
- delete the .git folder from the theme
- Move the theme somewhere else, and commit the change (make sure git picked up on the fact that the theme was removed)
- Move the theme back into content/themes and it should now be picked up as static files, as a part of the main ghost blog repository

Hope this helps anyone having issues committing changes to the theme to their blog and if anybody has a more elegant solution please feel free to comment!

**Comment by Kikobeats** [comment]
I have this problem when I try to deploy my ghost installation into a remote server using git hook, so thanks for write this in a issue.

Maybe could be useful add it in a section of the documentation related with deployment considerations. PR are welcome :-)

**Comment by Huanzhang89** [comment]
Ok, I'll have a go :) Will make a pull-request when done.

**Comment by Kikobeats** [comment]
awesome!
