### ISSUE TITLE
Is this ready for 0.8?

### ISSUE THREAD

**Issue by ambroselittle** [Kikobeats/uno-zen#193]
Just wondering if anyone has tested this to be compatible as-is with Ghost 0.8. I have version 2.5.7, FWIW.  Saw there may be some breaking changes: https://dev.ghost.org/get-your-theme-ready-for-0-8-0/

I'll probably try to test this weekend if nobody else has verified.

**Comment by Kikobeats** [comment]
not really! I'm going to update for be ready this weekend 😄

**Comment by ambroselittle** [comment]
If you want an extra tester, just let me know. :)

**Comment by AC6567** [comment]
@ambroselittle I am using 0.8 with this theme. Most is ok except for some issues with links to static pages on the home page. PR [here](https://github.com/Kikobeats/uno-zen/pull/194) to update.

**Comment by Kikobeats** [comment]
I'm going to release a minor version compatible with `0.8`. 

Stay tuned!
