### ISSUE TITLE
Several questions and suggestions

### ISSUE THREAD

**Issue by bestswifter** [Kikobeats/uno-zen#200]
1. It seems that I can't search Chinese characters, is it possible to support this?
2. I tried to use highlight.js to enable code highlight. However,it seems there is a conflict between the effect of highlight.js and default code highlight. So, can I disable default code highlight?
3. The time is incorrect, it shows "Nan days ago"

The address of my blog is https://bestswifter.com, you may take a look.

**Comment by bestswifter** [comment]
As an iOS developer, I can't fully understand how code highlight works. But after going through BOTH highlight.pack.js and your uno-zen.js, I guess some part of your uno-zen.js is related to highlight. So is it possible to remove some codes in uno-zen.js to disable default code highlight?

**Comment by Kikobeats** [comment]
First, update to last version, now search is based on google search 😄 .

highlight is based on prism.js, check this: https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#highlight-code-support.

I close the issue but feel free to reply.
