### ISSUE TITLE
How to share on Facebook

### ISSUE THREAD

**Issue by ygautomo** [Kikobeats/uno-zen#201]
Is there any way to share on facebook.
I've tried read the code but i don't understand.

There were 2 code similar in page.hbs and posts.hbs

```
<a alt="Tweet '{{title}}'" href="https://twitter.com/intent/tweet?text={{encode title}}{{encode ' »'}}&amp;hashtags={{tags separator="," autolink="false"}}&amp;url={{url absolute="true"}}">
        {{#if image}}<img id="post-image" src="{{image}}" alt="{{title}}">{{/if}}
        <h1 class="icon-reverse icon-social-twitter-post" id="post-title">{{title}}</h1>
      </a>
```

Could you please show me how to put code to share ghost post on facebook instead in twitter?

**Comment by Kikobeats** [comment]
Actually I don't, I suppose that Facebook has documentation about that.

This is the Twitter documentation: https://dev.twitter.com/web/tweet-button/web-intent.

I close the issue because is a question but feel free to reply 😄 .
