### ISSUE TITLE
Can't update prettify for the theme

### ISSUE THREAD

**Issue by azakordonets** [Kikobeats/uno-zen#202]
Hi, 

In the past i was using `<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>` tag in default.hbs file to be able to highlight code syntax. Now, this file is absent from googlecode.com and i was trying to update it with `<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>` tag, but when i update my default.hbs file, posts still load old tag and code doesn't get highlighting. Any ideas on where i'm looking wrong ?

**Comment by Kikobeats** [comment]
I don't know how prettify works, but basically you need

1) disable the uno-zen code highlight (css and js)
2) Link your code pretty

**Comment by azakordonets** [comment]
And how can i disable uno-zen code highlight ?

**Comment by Kikobeats** [comment]
Remove:

- https://github.com/Kikobeats/uno-zen/blob/master/gulpfile.coffee#L49
from the build

**Comment by Kikobeats** [comment]
Remove:
- https://github.com/Kikobeats/uno-zen/blob/master/assets/scss/modules/_prism.scss
- https://github.com/Kikobeats/uno-zen/blob/master/gulpfile.coffee#L49

from the build

**Comment by azakordonets** [comment]
Thanks.
