### ISSUE TITLE
Sliding "open" animation only happens if the navigation item is called "posts"

### ISSUE THREAD

**Issue by Windyo** [Kikobeats/uno-zen#203]
## Reproduction
- install ghost
- download uno-zen
- set uno-zen as a theme
- Go to the homepage and click on "posts"

**\+ Before modification > clicking on "posts" displays a sliding animation when opening posts**
- Go back to the admin panel
- in the Ghost navigation menu, change the "Posts" link name to something else, like "Hamburger"
- save
- Go to the homepage and  click on "Hamburger"

**\+ After modification > clicking on "hamburger" opens the posts with no sliding animation**
## Expected behavior

Clicking on a link mapped to #open should display the sliding animation weather the link is called "posts" or nor.

**Comment by Kikobeats** [comment]
not really, you can provide a selector for do that, check this:

https://github.com/Kikobeats/uno-zen/blob/master/assets/js/src/__init.coffee#L64

You can found documentation here: https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#open-button.

**Comment by Windyo** [comment]
No idea how I missed that. Thanks

**Comment by Kikobeats** [comment]
no problem 😄
