### ISSUE TITLE
Problem on openshift

### ISSUE THREAD

**Issue by pirakleous** [Kikobeats/uno-zen#206]
It seems that many things are missing

![image](https://cloud.githubusercontent.com/assets/8356922/20405992/39c6b456-ad14-11e6-9847-8f63a198bfcc.png)

**Comment by waja** [comment]
Just out of interest. You mean this [Openshift](https://en.wikipedia.org/wiki/OpenShift)?

**Comment by pirakleous** [comment]
yes

**Comment by Kikobeats** [comment]
I think that you need to setup your Ghost background/avatar.

I'm close that because is not a real issue related with the project but feel free to reply.
