### ISSUE TITLE
ghost 1.0 compatibility 

### ISSUE THREAD

**Issue by wassimseif** [Kikobeats/uno-zen#212]
Is this theme compatible with ghost 1.0?
I install it and the homepage was weird and not usable 
<img width="1189" alt="screen shot 2017-06-18 at 11 21 22 am" src="https://user-images.githubusercontent.com/7282773/27259310-7f9ff2c0-5418-11e7-8bdb-2aae52b750c9.png">

**Comment by Kikobeats** [comment]
Related to screenshot: You have to setup a cover and avatar image.

Related to Ghost: I don't know

**Comment by wassimseif** [comment]
Any documentation about them ?

**Comment by Kikobeats** [comment]
not really, you can be the first 😄

**Comment by Kikobeats** [comment]
https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md

**Comment by wassimseif** [comment]
I think there's an incompatibility issue with ghost 1.0. setting the publication logo in the `Admin`->`General` section did reflect on the theme. However, Setting the publication logo in the `Admin`->`General`  section did not affect the theme 
<img width="1207" alt="screen shot 2017-06-18 at 5 30 03 pm" src="https://user-images.githubusercontent.com/7282773/27261451-f2ad6620-544b-11e7-9fea-1cb2369d4cc6.png">
<img width="1578" alt="screen shot 2017-06-18 at 5 31 12 pm" src="https://user-images.githubusercontent.com/7282773/27261452-f3b8177c-544b-11e7-9744-8e0a2559a93b.png">

**Comment by wassimseif** [comment]
After a little debugging , the `{{ url(@blog.cover) }}` is empty

**Comment by wassimseif** [comment]
Found it! `@blog.cover` has been renamed to `@blog.cover_image`
