### ISSUE TITLE
Blog image broken on older Ghost version

### ISSUE THREAD

**Issue by pwnfoo** [Kikobeats/uno-zen#214]
#213 breaks all backward compatibility. Note that Ghost 1.0.0 is still in beta and not everyone will want to move onto the beta version. 

Background image breaks on all previous Ghost versions because of the `@blog.cover_image` change.

For anyone facing this issue : Change `@blog.cover_image` to `@blog.cover` in `partials/aside.hbs` and `error.hbs`
Current ghost version: `0.11.10`

**Comment by Kikobeats** [comment]
A workaround for support both:

```hbs
{{@blog.cover}} || {{@blog.cover_image}}
```

not sure if this is the correct syntax. Can you try it?

**Comment by Kikobeats** [comment]
Related: https://github.com/meteor/meteor/issues/4121

**Comment by pwnfoo** [comment]
I tried : 
```hbs
{{@blog.cover}} || {{@blog.cover_image}}
and 
{{@blog.cover}} OR {{@blog.cover_image}}
``` 
Both of them didn't work for me. Is there some sort of an IF syntax which can check if the variable is empty?

**Comment by pwnfoo** [comment]
I've sent in a PR to fix this. 

@Kikobeats, please review.
