### ISSUE TITLE
Ghost 1.x: Replace the {{author.image}} helper with {{author.profile_image}}

### ISSUE THREAD

**Issue by waja** [Kikobeats/uno-zen#219]
Verifying 2.9.6 with https://gscan.ghost.org/ result into:

*    partials/post-author.hbs: Please remove or replace {{author.image}} from this template

The image attribute in author context was replaced with profile_image.
Instead of {{author.image}} you need to use {{author.profile_image}}.
See the object attributes of author [here](https://themes.ghost.org/docs/author-context#section-author-object-attributes).

**Comment by waja** [comment]
I've prepared a RP #225, but https://gscan.ghost.org/ is still complaining (and GHOST itself I would guess too).

**Comment by Kikobeats** [comment]
what erros it throws?

**Comment by waja** [comment]
still as it would have not been touched (same as for "@blog.cover", which has a conditional implementation too):

* partials/post-author.hbs: Please remove or replace {{author.image}} from this template

The image attribute in author context was replaced with profile_image.
Instead of {{author.image}} you need to use {{author.profile_image}}.
See the object attributes of author here.
