### ISSUE TITLE
Post creation time with ghost 1.x absolute

### ISSUE THREAD

**Issue by waja** [Kikobeats/uno-zen#228]
With ghost prior 1.0 the creation time of a post is relative, only absolute when hovering over it:
![ghost_0 11](https://user-images.githubusercontent.com/1449568/28995452-a3957334-79e9-11e7-8c0c-c8769d70aee6.png)
With 1.0 it is absolute even without hovering:
![ghost_1 5](https://user-images.githubusercontent.com/1449568/28995451-a3871550-79e9-11e7-95c6-11efcbd274e0.png)

**Comment by Kikobeats** [comment]
Probably just is need how the time is rendered from the backend.

Can you convert it into a PR? 😄
