### ISSUE TITLE
Messed up front page 

### ISSUE THREAD

**Issue by waqaskhan137** [Kikobeats/uno-zen#229]
I have uploaded the theme and put 

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.6/zepto.min.js"></script>
<script>jQuery = Zepto</script>`

in the Code injection in the footer but still, i see this view of my website with this theme. 

<img width="1240" alt="screen shot 2017-08-12 at 4 55 41 am" src="https://user-images.githubusercontent.com/4752256/29235787-cb30849c-7f1b-11e7-8e55-96594051e6b2.png">

**Comment by Kikobeats** [comment]
add a background image in ghost panel

**Comment by ranawaqas-ai** [comment]
I have added blog cover and logo but still 
<img width="934" alt="screen shot 2017-08-12 at 3 08 11 pm" src="https://user-images.githubusercontent.com/4752256/29239786-21c68488-7f70-11e7-8f36-10101e5000e4.png">
<img width="1032" alt="screen shot 2017-08-12 at 3 08 51 pm" src="https://user-images.githubusercontent.com/4752256/29239793-4877caf6-7f70-11e7-99b0-3c8fdfa10642.png">

**Comment by Kikobeats** [comment]
oh, the last version of this theme use Ghost 1.x

**Comment by von1000** [comment]
Did you solve it? I meet the same problem. My version is Ghost-CLI 1.8.1.

**Comment by ranawaqas-ai** [comment]
@alittlealone I couldn't fix the issue so I stopped using the theme. Please update if it works for you.
