### ISSUE TITLE
integrates with zoom

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/uno-zen#23]
https://github.com/fat/zoom.js

**Comment by Kikobeats** [comment]
alternative to zoom: https://github.com/ROUND/enhance.js

@kutyel check this. When I saw zoom.js in the past I feel that need many dependencies to work, and one of the thing that I want to ensure with this project is that the minimal css/js code to work well. Maybe the approach of enhance implementation is more lightweight

**Comment by kutyel** [comment]
Nice! I will have a look and try to implement it as soon as I have a minute off, thanks! :smile:

**Comment by Kikobeats** [comment]
I tested this today, but the default zoom behavior break the interface and need a lot to effort to work correctly. On the other hand is adding code that I feel that in the 95% of the case the people will not do click in the image.

For the moment I close this.
