### ISSUE TITLE
About SSL

### ISSUE THREAD

**Issue by pupboss** [Kikobeats/uno-zen#24]
Hi, there

My site have a SSL certificate, and normally there is a small lock in address field, like this 

![](http://ww4.sinaimg.cn/large/85c68139tw1esfed7oaoij20bu01mmx6.jpg)

but now I use uno-zen, it only appear in 404 page, you can see it [here](http://pupboss.com/404)

It can't appear in [index](https://pupboss.com/) and post page, and the theme I used before don't have this issue, I guess it may caused by the top progress bar.

What's more, when I reload the page, the lock will flash across and then disappear.

Would you like to tell me how to reappear the lock or how to cancel the top progress bar :)

**Comment by Kikobeats** [comment]
Sure? I'm seeing HTTPS in the post page

![](http://i.imgur.com/UuZYCmU.png)

**Comment by pupboss** [comment]
Oh sorry, it was my fault, I forgot to check the address, the site's address is https, but the lock don't appear 

Maybe it was caused by safari.

![](http://ww2.sinaimg.cn/large/85c68139tw1esflibtwa8j20cv02bt8o.jpg)
![](http://ww4.sinaimg.cn/large/85c68139tw1esflilw1lbj2079019q2u.jpg)
