### ISSUE TITLE
Please, add my blog into showcase

### ISSUE THREAD

**Issue by dinchamion** [Kikobeats/uno-zen#25]
Awesome work on the theme! :-)

The URL of my blog is: http://www.dinchamion.com

**Comment by Kikobeats** [comment]
You can see it in the next showcase, thanks! :-)

PS: Remember change the favicon as well :P

**Comment by dinchamion** [comment]
Thanks! :-)

On the favicon - I've been trying to set my own favicon, but for some reason no matter what I do, it wouldn't change it. I even emptied out the assets/img/ folder, and unzipped the new favicons, still nothing.

I'm fair sure it's a user problem, so I'd rather not open an issue (especially since nobody else seems to have it).
