### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by kutyel** [Kikobeats/uno-zen#26]
The URL of my blog is: www.flaviocorpa.com

Love Ghost, love the theme, any advise improving the mobile version?

I've seen that the default casper theme looked awesome in mobile devices, but not yet this theme :(

I may improve it in my fork, but have little time to spend.

Thanks in advance!

**Comment by Kikobeats** [comment]
Casper I supported officially by the Ghost team, meanwhile I'm just a man. I try to do my best effort :-)

what's happens in the mobile version? I think that is enough. Any error experience? If you can open independent issues being more specific I can try ho fix it.

Btw, I close this issue and add your blog for the next showcase!

**Comment by kutyel** [comment]
Thank you so much Kiko, you're doing a great job! I'll add another issue with some screenshots to show you what I mean ;)

**Comment by ArchonFreak** [comment]
https://archonfreak.io/i/AF-318-0.jpg
Something New
