### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by blackxored** [Kikobeats/uno-zen#32]
This theme is really awesome. I was ready to pay for a theme but this looks gorgeous and provides everything I need. I can help with improving the mobile layout if you need a hand, since I don't see myself switching away from it anytime soon. 

My blog is at http://adrianperez.org, and I've done a poor job of showcasing this theme there, but I'm hoping you can mention it anyways ;) LOL

**Comment by Kikobeats** [comment]
Help is always welcome. Check the issue section and decide if you could
improve something.

You have a donate button in the README as well. I will add your blog this
afternoon! I'm not near to a computer now :-)

**Comment by Kikobeats** [comment]
added! :)
