### ISSUE TITLE
Add Previous/Next post links

### ISSUE THREAD

**Issue by jloh** [Kikobeats/uno-zen#35]
It'd be great if there was Next/Previous post links as outlined here (http://themes.ghost.org/v0.6.0/docs/prev_next_post)

I'm happy to have a crack but my CSS skills are non-existent

**Comment by Kikobeats** [comment]
Definitely yes! could be awesome for the next minor version :-)

**Comment by Kikobeats** [comment]
available in next `2.3` releases :-)
