### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by waldaldo** [Kikobeats/uno-zen#36]
The URL of my blog is: http://eduardohurtado.info 

:)

**Comment by Kikobeats** [comment]
customize the theme pls :)

**Comment by waldaldo** [comment]
## Sorry, I just updated to last versión ;)

Eduardo Hurtado Palacios
F: 91614494
*Enviado desde un dispositivo móvil
El jul. 30, 2015 6:24 AM, Kiko Beats notifications@github.com escribió:customize the theme pls :)

**Comment by Kikobeats** [comment]
open a new issue when you customize it
