### ISSUE TITLE
I replaced the cover.jpeg but still its not changing ?

### ISSUE THREAD

**Issue by waqaskhan137** [Kikobeats/uno-zen#4]
Hi
I have replaced the cover.jpeg with another .jpeg which is of the same resolution 1920x1080 but it doesn't take effect even after restarting the ghost?

Thanks,

**Comment by Kikobeats** [comment]
It's a problem that I fix in the new 2.0 version! just clone the repository instead of use the last tag version.

**Comment by ranawaqas-ai** [comment]
And it has the same issue with the Favicon

**Comment by Kikobeats** [comment]
try now with the new 2.0 tagged version!

Also I completed the wiki with more useful information :-)
