### ISSUE TITLE
Getting errors with fastclick & other plugins

### ISSUE THREAD

**Issue by robincsamuel** [Kikobeats/uno-zen#45]
I think those plugins are not correctly compiled into uno.js

Please check https://github.com/Kikobeats/uno-zen/blob/master/gulpfile.coffee#L37

I got it working when i changed that 'assets/vendors' to 'bower_components'.

**Comment by Kikobeats** [comment]
[this file](https://github.com/Kikobeats/uno-zen/blob/master/.bowerrc) setup the directory for the bower components

**Comment by Kikobeats** [comment]
I have the last version deployed on kikobeats.com and I don't have javascript errors in the console. Can I inspect your blog url?

**Comment by Kikobeats** [comment]
I compiled again the assets and rebuild the `2.3.1` tag, try to deploy it again

**Comment by robincsamuel** [comment]
Yes please. http://robinz.herokuapp.com/

I'll try udpating
