### ISSUE TITLE
Theme installation issue

### ISSUE THREAD

**Issue by nikolay-matev** [Kikobeats/uno-zen#48]
Hello, it's my first time installing a theme for Ghost and I have some trouble doing it. I am stuck with my page showing up like this and I am unable to fix it, so here I am asking for your help. Thanks!

![Screenshot](http://i.imgur.com/4ZrY8w5.png)

**Comment by Kikobeats** [comment]
I think that all is ok, just you need to setup the cover image and other stuff.

Check the [documentation](https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md). Also I just release a new version, so be sure that you have the last theme version (download again from [releases](https://github.com/Kikobeats/uno-zen/releases) section and replace the files).
