### ISSUE TITLE
Text cut off in search panel

### ISSUE THREAD

**Issue by jwir3** [Kikobeats/uno-zen#50]
See the following screenshot of a new blog I just created.

<img width="1436" alt="screenshot" src="https://cloud.githubusercontent.com/assets/997106/9399795/0d5974ea-477f-11e5-849e-d3ed53415dc7.png">

The text in the search input is cut off on the top and bottom.

**Comment by jwir3** [comment]
I am using Firefox 39.0.3 on Mac OSX

**Comment by jcdenton** [comment]
Besides the text being cut in FF, the search icon is displaced a bit to the bottom in both Chrome and FF. 
Firefox 39.0.3 and 40.0.2 on Windows 
<img width="244" alt="search_input" src="https://cloud.githubusercontent.com/assets/156504/9405124/abe53e0e-47fd-11e5-80ea-714a92670edb.png">
Chrome 46.0.2486.0 dev-m on Windows
<img width="233" alt="search_input_chrome" src="https://cloud.githubusercontent.com/assets/156504/9405170/2302dc26-47fe-11e5-8e8f-a6f65cae303e.png">
It seems, that removing `height: .4rem;` for `#search-field` (https://github.com/jcdenton/uno-zen/commit/f3cefa4ab3eddd1ca4eaadaa7e3d860e79b3f488) fixes both issues in both browsers and slightly improves look in IE11 (_sic!_).
It would be nice to also check Safari and others (though a WebKit-based Opera shows the same way as Chrome).

**Comment by Kikobeats** [comment]
Nice, but I want to stylize the width of the form... how to?

**Comment by jcdenton** [comment]
How does it affect "width"? Did you mean "height"? If so, just play with decreasing padding and increasing height, e.g.:

``` css
height: 1.5rem;
padding: 1% 5px 2% 18px;
```

**Comment by Kikobeats** [comment]
yes, height, sorry 😅

**Comment by Kikobeats** [comment]
status of this: I want to check later in dev and if works fine this afternoon will be integrated
