### ISSUE TITLE
Hosting on openshift

### ISSUE THREAD

**Issue by karan-kapoor90** [Kikobeats/uno-zen#55]
Hi

I've hosted Ghost on openshift and I've gotten my personal domain abc.com to point to openshift hostname abc-domain.rhcloud.com using a cname record as per openshift guidelines. 

The problem is that when I go to abc.com/ghost or any other URL within the ghost admin app, my url stays as abc.com .. but when I use your theme and except from the homepage, I navigate to any other URL other than the homepage, such as abc.com/myBlog , the url changes to abc-domain.rhcloud.com/myBlog

Any idea why this could be happening?

**Comment by jcdenton** [comment]
I've just checked your http://www.karankapoor.in/ - there is the default theme now, but blog logo on the left and navigation links in the menu on the right still point to the http://karankapoor-woxpas.rhcloud.com/.
The only links that point to the http://www.karankapoor.in/ are relative, all absolute links point to the *.rhcloud.com.
Looks like **not a theme-related problem.**
Though, I recommend checking Ghost documentation and URL setting in your `config.js` or double-checking DNS config.
