### ISSUE TITLE
All the links on blog are opening in new tab for blog hosted in subdirectory

### ISSUE THREAD

**Issue by kushdilip** [Kikobeats/uno-zen#59]
I am hosting my blog in a subdirectory and all the links in sidebar are opening in new tab because of below [code](https://github.com/Kikobeats/uno-zen/blob/4755ace9581019ac9e2b260889296d4420b49e61/assets/js/src/main.coffee#L20)

```
if Uno.is 'device', 'desktop'
    $(document.links).filter ->
      @hostname != window.location.hostname
    .attr 'target', '_blank'
```

For now I have commented above code to get it work.

See the [blog](http://www.kushdilip.com/blog/)

**Comment by Kikobeats** [comment]
Yes, these piece of code of for automatically open external links in a new tab.

Exists a [lot of snippets for do it](https://www.google.es/search?q=jquery+open+external+links+in+new+window&oq=jquery+open+external&aqs=chrome.1.69i57j0l5.3308j0j1&sourceid=chrome&es_sm=119&ie=UTF-8). I understand the current used in the theme is too simple for your use case and doesn't handle with subdomains.

If you can try to resolve and create a PR I would appreciate it. Check the documentation for know how to setup the dev environment. I think that will can be relatively easy to resolve :-)

**Comment by Kikobeats** [comment]
@kushdilip can you try this instead?

``` coffee
    $('a').not('[href*="mailto:"]').click ->
      if this.href.indexOf(location.hostname) is -1
        window.open $(this).attr 'href'
        false
```

**Comment by Kikobeats** [comment]
I change the code and will be avaiable in `2.5.0`.

**Comment by kushdilip** [comment]
@Kikobeats Thanks :+1: I had achieved this manually but having it implemented in theme itself helps more.
