### ISSUE TITLE
Incorrect margin-top in 404 page with different viewports

### ISSUE THREAD

**Issue by mickeyhoh** [Kikobeats/uno-zen#68]
Hi Kiko
Thanks for aligning the background images for both mobile devices vs desktop/notebook to make them consistent for release 2.5.0. Similarly thanks for fixing the Error bug.

As mentioned earlier, scrolling is required for the Error page, to access the Panic and Safe buttons. I would suggest to reduce the page size, to minimize scrolling, for UX purposes.

Once again, keep up the good work!

**Comment by mickeyhoh** [comment]
My current notebook resolution is 1366 X 768.
My mobile device is Android with 5 inch screen.
Hope this helps?

**Comment by Kikobeats** [comment]
something that I don't understand is why you say cover.jpg. This file is not more longer necessary, now automatically is resolved from the setting in the admin panel.

btw, what browser do you use? I tested responsive version using chrome dev tools and looks well :-(

**Comment by mickeyhoh** [comment]
![image](https://cloud.githubusercontent.com/assets/11407891/9797207/9160fdf4-582c-11e5-9f77-1c90723f703b.png)
The above is the screenshot via my browser. What you see is the whole screen (with the browser parts cropped off), as well as the vertical scrolling bar on the right.
This clearly shows that the web page is too big for my browser even on my resolution mentioned earlier.
Shouldn't the page auto-adjust its size somehow?
For notebook, I am using Chrome v45 on Windows 7.

**Comment by mickeyhoh** [comment]
Lets forget about the cover.jpg. I understand that you have improved the codes. Sorry for the misunderstanding.
If I view the error page on my Android phone using Chrome 45 as well, the same scrolling is required and the last words I could see are 'What happens now?' before I need to scroll down to see the 2 buttons.

**Comment by Kikobeats** [comment]
the problem is related with the viewport height, I want to fix quickly :-)

**Comment by mickeyhoh** [comment]
Thanks Kikobeats! All looks good now. I used your latest release :)
You have been very fast and good. Well done!
