### ISSUE TITLE
Theres is weird jQuery error .. in GG console.

### ISSUE THREAD

**Issue by 54853315** [Kikobeats/uno-zen#69]
Here is the thing.

![qq20150910-1 2x](https://cloud.githubusercontent.com/assets/1081252/9784950/2bb414e6-57e1-11e5-96da-dbae03bd4630.jpg)

**Comment by Kikobeats** [comment]
jQuery is provided by CDN: https://github.com/Kikobeats/uno-zen/blob/master/default.hbs#L24

If you are editing the theme locally be sure to have `gulp` running.

what version of the theme are you using? type `Uno.version` in the console.

**Comment by krestjaninoff** [comment]
Hmm, that is interesting - I have a kind of similar error too:

```
Uncaught ReferenceError: $ is not defined uno.js?v=ce03d389c7:8(anonymous function)
```

"Uno" object is undefined in my console, but according to the CHANGELOG I'm using # 2.4.0 (2015-08-31). And no - I don't have any reference to jQuery in default.hbs :(

Adding the link solves the problem, so the only question is - why do we need jQuery if blog seems to work correct without it (except the error in the console)?

**Comment by Kikobeats** [comment]
Just Uno `2.5.x`  is compatible with Ghost `0.7`. so I suspect that you updated Ghost but not the theme, right? Because Ghost `0.7` removed jQuery support and in Uno `2.5.0` I added it as dependency. Install the last version and try again...

**Comment by mickeyhoh** [comment]
I am not getting any error but I have updated to Ghost 0.7 and found this in the Blog Footer:



<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

Should I be remove this line or just leave it alone? Would it affect this Uno Zen theme or other themes in any way?

**Comment by Kikobeats** [comment]
I going to close this because I understand that using the last version of the theme and the last version of Ghost, all works fine.

I don't want support old versions of the theme because Ghost is under development preview and I want to keep the theme the most align with the Ghost API possible.
