### ISSUE TITLE
Twitter and linkedIn Icon doesn't show properly in Firefox ?

### ISSUE THREAD

**Issue by waqaskhan137** [Kikobeats/uno-zen#7]
It works fine in Chrome but when you try it in Mozilla Firefox those two like 
![Abnormal Behaviour](https://cloud.githubusercontent.com/assets/4752256/6413486/c467a280-beb1-11e4-90c8-d0bb44795cf6.png)

**Comment by Kikobeats** [comment]
I checked with the last firefox version and works fine, I think that is more a problem of your code, can you paste here?

**Comment by ranawaqas-ai** [comment]
Which code do you need to see ?
