### ISSUE TITLE
strange error in chrome console

### ISSUE THREAD

**Issue by tankiJong** [Kikobeats/uno-zen#70]
I used the latest version of the theme, and got the following error:

```
Uncaught TypeError: ((m.event.special[e.origType] || (intermediate value)).handle || e.handler).apply is not a function

jquery-1.11.3.min.js
```

**Comment by Kikobeats** [comment]
I know, but I don't know why.

When I enter in my web first time, I see the error, but I refresh the same page, the error is not here.

**Comment by tankiJong** [comment]
I found that, when resizing the page, this error occurs. You may inspect this by resizing the  box of 'Review elements'. So I think this is relevant to the js about layout 

By the way, the Blog name and Avatar disappeared..

**Comment by Kikobeats** [comment]
I want to release `2.5.2` today with more bugfix and I want to include this, just need to found the bug!

**Comment by tankiJong** [comment]
By the way, the Blog name and Avatar disappeared..

**Comment by Kikobeats** [comment]
I found it!

before

``` coffee
el.dataset.device = Uno.device()
$(window).on "resize", Uno.device()
$(window).on "orientationchange", Uno.device()
```

after 

```
setDevice = -> el.dataset.device = Uno.device()
setDevice()
$(window).on "resize", setDevice
$(window).on "orientationchange", setDevice
```

or better, just:

```
el.dataset.device = Uno.device()
```

**Comment by tankiJong** [comment]
perfect! wait for your release!
