### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by mickeyhoh** [Kikobeats/uno-zen#71]
I am not sure if this is a bug or an intended feature.
The first page I see when I view the blog using a desktop/notebook is the Cover of the blog.
However, the page page I see when I view it using a mobile device is the list of posts.
Is there a way to have the Cover of the blog as the first page in a mobile device?

**Comment by Kikobeats** [comment]
At this moment is not possible see the cover page in the mobile/tablet version, we are working on this.

See #29 for more details!

**Comment by mickeyhoh** [comment]
Thanks Kikobeats.
At least you folks have explored it.
Your theme is great and I am hoping it that the landing page could be improved like Casper. Will await your future update ;)
