### ISSUE TITLE
Can't enable disqus support to posts

### ISSUE THREAD

**Issue by azakordonets** [Kikobeats/uno-zen#75]
Hi, really like your ghost theme. I'm almost done making it work for myself, but the only thing i could fix is disqus support. I have tried already to insert into Blog Header disqus_shortname variable with both my own shortname into disqus and the shortname of my channel in disqus. What am i missing ?

**Comment by azakordonets** [comment]
Fixed it by adding to post.hbs after  `</article>` tag 

``` html
<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = '{disqus_shortname_put_here}'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscrip$
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
```

and restarting the service

**Comment by Kikobeats** [comment]
are you try [this](https://github.com/Kikobeats/uno-zen/blob/master/DOCUMENTATION.md#comments)?

**Comment by azakordonets** [comment]
I did, but that didn't help - i was getting "We were unable to load Disqus." message on every post page.

**Comment by Kikobeats** [comment]
strange... are you setup the shortanme on disqus? my website is running correctly 😕

**Comment by azakordonets** [comment]
I think so.. It is possible that i might miss something during disqus setup, but right now the solution i mentioned works, so i'm good. Thanks again for a nice theme:) I was using Uno before but i very disliked that the width of every post was really small.

**Comment by jorge-sanz** [comment]
Hi, guys! I have the same problem here... I tried the @azakordonets solution but nothing went well.
