### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by painhardcore** [Kikobeats/uno-zen#76]
Do i need smth to make search working??I use latest theme.
I know that for Ghost i need to use GhostHunter....

**Comment by Kikobeats** [comment]
exactly what he means when he says that does not work?
what is your blog url?

**Comment by painhardcore** [comment]
It simply nothing happens when i trying to search for smth.
http://blog.yurchenkov.ru/
Maybe i need to do some extra actions?

**Comment by hnykda** [comment]
I have same problem. When I search for some text, it just refresh the right bar with posts, but nothing is filtered.

**Comment by Kikobeats** [comment]
@painhardcore in your website in JavaScript console I see:

`$ is not defined`

read the release note => https://github.com/Kikobeats/uno-zen/releases/tag/2.5.2

In addition, (for @kotrfa) Ghost doesn't implement a search, so the current solution is based in a RSS scrapping. It's not perfect and in my opinion needs a good quantity of posts have results.
