### ISSUE TITLE
Menu button doesn't work on small screen

### ISSUE THREAD

**Issue by hnykda** [Kikobeats/uno-zen#78]
Hello,

I'm trying to install this theme but I'm quite surprised that on smaller screen I can't open the menu by the menu button in top left corner. Even when I try your [blog](http://kikobeats.com/#open) and resize my screen on my laptop so the menu disappears, when I click on it I just get blank screen. Same on my mobile phone (Android.)

**Comment by hnykda** [comment]
Sorry, I don't know why, now it worked. Maybe some connection problem. Sorry for that.

**Comment by Kikobeats** [comment]
A Little bit weird. When you resize first need to reload to force JavaScript detect the resolution. 

Mobile behavior really I don't know. I tested the theme on iPad and iPhone 6 and works fine... I suppose that depend of the resolution of your Android. I know that at this moment doesn't work perfect for little screens (see #72). If you detect something bug please provide gif or something to undertand the problem :)

**Comment by Kikobeats** [comment]
@kotrfa :+1:

**Comment by hnykda** [comment]
Yeah, I've just notice that it depends on the fact if you open it on full screen and then resize or you loaded small already.
