### ISSUE TITLE
Full screen switch (#open) not working 

### ISSUE THREAD

**Issue by hnykda** [Kikobeats/uno-zen#79]
Hello,

for some reason I can't mimic the behaviour of the first [example](http://www.evilsocket.net/#open) - when you open the blog, it's fullscreen and you can click on links to blog or on photo/logo, so it will take you to the blog (and viceversa). But on my blog this doesn't work and surprisingly not on other examples, e.g. [this one](http://www.evilsocket.net/#open). The behaviour is even different like [here](https://adrianperez.org/), where you get full screen at the beginning, but can't get back after clicking from post view to fullscreen.

Do you know what might be the problem?

**Comment by Kikobeats** [comment]
If in `evilsocket.net` I open devTools and I type `Uno.version` nothing happens. But in the last `adrianperez.org` the Uno version is `2.2.1`.

1) try to update the theme frequently (right now las version is `2.5.2`)
2) If you change something of the theme remember run `gulp build` to be sure before upload your build in your server. (more information about the development environment in the documentation).
