### ISSUE TITLE
The inconsistent behaviour because of jquery (not)included

### ISSUE THREAD

**Issue by hnykda** [Kikobeats/uno-zen#80]
Hello,

I've just posted two issues because the behaviour on my blog was just different from what I've seen on examples. First one was that menu button on small screens didn't work and the second one was opening fullscreen at start.

The reason for this behaviour is that in the theme there is no jquery dependency! After adding it to the ghost header by `<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>`, everything magically works! I would really at least mention it in README, because this theme unusable on small screens.

Thanks for great work!

**Comment by Kikobeats** [comment]
Since Ghost 7.x is not injected by Ghost foot automatically... I posted a note in the last release but yes, is necessary update the Readme and put special attention at this point. I'm going to do it.
