### ISSUE TITLE
Profile_title and profile_resume not working

### ISSUE THREAD

**Issue by Elinos** [Kikobeats/uno-zen#87]
I just installed your theme here - https://tsghostblog.herokuapp.com
But it doesn't seems to properly inject the variables in the template, so I can't change them :(.

**Comment by Kikobeats** [comment]
I suppose that you closed it because you read the documentation 😁

**Comment by Elinos** [comment]
I found out that you actually need to upload logo and cover picture in order to show them :)
Btw in the documentation, there is a slide mislead in the Cover section - "Go to Ghost Admin panel -> **Code Injection** -> Blog Cover".
I think it should be "Go to Ghost Admin panel -> **General** -> Blog Cover"?

**Comment by Kikobeats** [comment]
You're right. I updated the documentation, thanks!
