### ISSUE TITLE
Keeping uno-zen up-to-date

### ISSUE THREAD

**Issue by ghost** [Kikobeats/uno-zen#90]
Hey,
whats the best way to keep uno-zen theme up-to-date? I've made some changes to the code. Should I use git? For now I've installed it with the release archiv an extracted it.

```
npm install uno-zen && mv node_modules/uno-zen uno-zen && (trash node_modules || rm -r node_modules)
uno-zen@2.5.4 ../../node_modules/uno-zen
mv: der Aufruf von stat für „node_modules/uno-zen“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
```

Doesn't work for me.

Greetings,
Loo

**Comment by Kikobeats** [comment]
You're right, is not a good way to install and make easy update the theme.

I updated the command to install the theme. Now, I'm thinking about an easy way to update... any suggestion?

**Comment by ghost** [comment]
I'm not that familiar with git and coding in general

# Installation

Enter in the theme folder (content/themes) of your Ghost installation and type:

`git clone https://github.com/Kikobeats/uno-zen.git`

# Update Installation

Enter in the uno-zen folder (content/themes/uno-zen) of your Ghost installation and type:

`git pull origin master`
What happens here to changes I made local?

The last step is to build everything?
`npm install && bower install && gulp build`

**Comment by Kikobeats** [comment]
I'm going to avoid npm install and create a custom scripts based in git commands. soon!

**Comment by Kikobeats** [comment]
I added a installation / update scripts in the next `2.5.5 version`. Readme of the project is updated as well. Thanks! :-)
