### ISSUE TITLE
I guess the color of inline code block has some problem

### ISSUE THREAD

**Issue by nocheers** [Kikobeats/uno-zen#92]
Thank you for your great work on Ghost Theme. But now when I use the markdown to write some inline codes(like `bash`,`sudo npm install`), the color of inline code turns grey after I publish my article.
But it is red when I do the preview of this article. Could you help me to solve it?

**Comment by Kikobeats** [comment]
It's not supported because is necessary load too much css... I prefer create a simple gist and embed it in the post.
