### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by Couby** [Kikobeats/uno-zen#96]
Hi,

I wanted to update the theme (uno-zen-2.2.3 for the moment) on my Ghost. I choose to make a fresh install of it.
I have the following error : 
`sh: 3: /couby/ghost/content/themes/uno-zen/scripts/utils.sh: Syntax error: "(" unexpected`

The install script didn't executed fully in this case.

It seems the bash of my VM doesn't accept `function xxx(){}` commands :-/
I don't know if there can be other users in the same case...

I noticed removing `function` line 3 of utils.sh makes it working.

Then I made a install2.sh in order to finish install.

```
. "$PWD"/scripts/utils.sh

welcome

echo "Getting the repository tagged commits"
git fetch --tags

echo "Resolving the latest tagged version"
latestTag=$(git describe --tags "$(git rev-list --tags --max-count=1)")

echo "Creating a stable branch from the latest tagged version"
git checkout "$latestTag"
git checkout -b stable

echo "\nTheme Installed Successful! Enjoy :-)"
```

If that can help someone else in the same case.

**Comment by Kikobeats** [comment]
what version of batch are you sing? type `bash --version`, in my case:

``` bash
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

btw, I see that is a syntax problem (http://stackoverflow.com/a/6347145). I'm going to fix this for the next version. Thanks! :-)
